package br.com.abdiel.Enum;

public enum equipmentList {
    TANQUINHO, LAVAESECA, LAVAROUPAS, GELADEIRA, SIDEBYSIDE, FRIGOBAR, FOGAO, ARCONDICIONADO, MICROONDAS, FREEZER, LAVALOUCAS, SECADORA, AQUECEDORAGUA, DEPURADOREXAUSTOR
}
